#!/bin/sh
jekyll build;
git add .

echo 'Enter the commit message:'
read commitMessage

git commit -m "$commitMessage"
git push;
#echo 'Enter the name of the branch:'
#read branch
#git push origin $branch
open http://elegance.abdennoor.com;
read
